project: ivtlr
save_path: /home/ma-user/work/lbx/IVT-LR/qwen_vl/output
name: m3cot_qwen2vl_IVTLR

# 添加数据集控制字段
dataset_name: m3cot  # 选项: 'm3cot' 或 'scienceqa'

epochs_per_stage: 4
max_latent_stage: 5
pad_latent_to_max: True

load_model_path: None
seed: 0
resume: 0
bf16: True

# 原本是2,m3cot用的4，后面都用2吧？
batch_size_training: 2

debug: False
gradient_accumulation_steps: 8
num_epochs: 16
lr: !!float "4e-5"